# Adapt a build-directory copy; keep the pinned upstream submodule pristine.
# Fail closed if the insertion point changes on a GGML update.
set(_vitpose_vk_source "${CMAKE_CURRENT_SOURCE_DIR}/ggml/src/ggml-vulkan/ggml-vulkan.cpp")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_vitpose_vk_source}")
file(READ "${_vitpose_vk_source}" _vitpose_vk_text)
set(_vitpose_vk_anchor "    vk_pipeline pipeline = ggml_vk_guess_matmul_pipeline(ctx, mmp, ne01, ne11, aligned, qx_needs_dequant ? f16_type : src0->type, effective_src1_type);")
string(FIND "${_vitpose_vk_text}" "${_vitpose_vk_anchor}" _vitpose_vk_position)
string(FIND "${_vitpose_vk_text}" "${_vitpose_vk_anchor}" _vitpose_vk_last_position REVERSE)
if(_vitpose_vk_position EQUAL -1 OR NOT _vitpose_vk_position EQUAL _vitpose_vk_last_position)
  message(FATAL_ERROR "ViTPose Vulkan tile insertion point changed; review the GGML adapter or set GEMX_VITPOSE_TILES=OFF")
endif()
string(REPLACE "${_vitpose_vk_anchor}" "${_vitpose_vk_anchor}\n#include \"vulkan_vitpose_tiles.inc\"" _vitpose_vk_text "${_vitpose_vk_text}")
set(_vitpose_vk_copy "${CMAKE_CURRENT_BINARY_DIR}/gemx-vulkan/ggml-vulkan.cpp")
file(CONFIGURE OUTPUT "${_vitpose_vk_copy}" CONTENT "${_vitpose_vk_text}" @ONLY)
get_target_property(_vitpose_vk_sources ggml-vulkan SOURCES)
set(_vitpose_vk_replaced FALSE)
foreach(_vitpose_vk_entry IN LISTS _vitpose_vk_sources)
  if(_vitpose_vk_entry STREQUAL "ggml-vulkan.cpp" OR _vitpose_vk_entry STREQUAL "${_vitpose_vk_source}")
    list(REMOVE_ITEM _vitpose_vk_sources "${_vitpose_vk_entry}")
    list(APPEND _vitpose_vk_sources "${_vitpose_vk_copy}")
    set(_vitpose_vk_replaced TRUE)
  endif()
endforeach()
if(NOT _vitpose_vk_replaced)
  message(FATAL_ERROR "Cannot locate GGML Vulkan compilation unit for ViTPose tile adapter")
endif()
set_property(TARGET ggml-vulkan PROPERTY SOURCES "${_vitpose_vk_sources}")
target_include_directories(ggml-vulkan PRIVATE
  "${CMAKE_CURRENT_SOURCE_DIR}/src"
  "${CMAKE_CURRENT_SOURCE_DIR}/ggml/src/ggml-vulkan")
